In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

# Carga de datos y exploración inicial
- Cargo el archivo excel con todas las hojas al mismo tiempo

In [2]:
df_mapa = pd.read_excel('../datasets/mapa_conectividad.xlsx')

In [3]:
df_mapa.shape

(4305, 16)

In [4]:
df_mapa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4305 entries, 0 to 4304
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Provincia       4305 non-null   object
 1   Partido         4305 non-null   object
 2   Localidad       4305 non-null   object
 3   Población       4305 non-null   int64
 4   ADSL            4305 non-null   object
 5   Cablemódem      4305 non-null   object
 6   Dial Up         4305 non-null   object
 7   Fibra óptica    4305 non-null   object
 8   Satelital       4305 non-null   object
 9   Wireless        4305 non-null   object
 10  Telefonía Fija  4305 non-null   object
 11  3G              4305 non-null   object
 12  4G              4305 non-null   object
 13  Link            4293 non-null   float64
 14  Latitud         4305 non-null   float64
 15  Longitud        4305 non-null   float64
dtypes: float64(3), int64(1), object(12)
memory usage: 538.3+ KB

In [5]:
df_mapa.head()

,Provincia,Partido,Localidad,Población,ADSL,Cablemódem,Dial Up,Fibra óptica,Satelital,Wireless,Telefonía Fija,3G,4G,Link,Latitud,Longitud
0,BUENOS AIRES,25 de Mayo,25 de Mayo,23408,SI,SI,--,--,SI,SI,SI,SI,SI,6854100.0,-35.433939,-60.173121
1,BUENOS AIRES,25 de Mayo,Agustín Mosconi,280,--,--,--,--,--,--,SI,--,--,6854010.0,-35.739217,-60.559063
2,BUENOS AIRES,25 de Mayo,Del Valle,899,SI,--,--,--,SI,--,--,SI,--,6854020.0,-35.897345,-60.731609
3,BUENOS AIRES,25 de Mayo,Ernestina,145,SI,--,--,--,--,--,SI,--,--,6854030.0,-35.270234,-59.557503
4,BUENOS AIRES,25 de Mayo,Gobernador Ugarte,547,--,--,--,--,--,SI,--,--,--,6854040.0,-35.164397,-60.081358

In [6]:
print(df_mapa.isnull().sum())

Provincia          0
Partido            0
Localidad          0
Población          0
ADSL               0
Cablemódem         0
Dial Up            0
Fibra óptica       0
Satelital          0
Wireless           0
Telefonía Fija     0
3G                 0
4G                 0
Link              12
Latitud            0
Longitud           0
dtype: int64

In [7]:
# Elimino las filas que contienen valores nulos
df_mapa.dropna(inplace=True)

- Verifico si quedo datos nulos

In [8]:
print(df_mapa.isnull().sum())

Provincia         0
Partido           0
Localidad         0
Población         0
ADSL              0
Cablemódem        0
Dial Up           0
Fibra óptica      0
Satelital         0
Wireless          0
Telefonía Fija    0
3G                0
4G                0
Link              0
Latitud           0
Longitud          0
dtype: int64

### Normalizo el dataset

- Comienzo con las mayusculas

In [9]:
df_mapa.columns = df_mapa.columns.str.lower()

- Eliminar Espacios en Blanco y Reemplazar con Guiones Bajos

In [10]:
df_mapa.columns = df_mapa.columns.str.replace(' ', '_')

- Elimino caracteres especiales

In [11]:
df_mapa.columns = df_mapa.columns.str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df_mapa.columns = df_mapa.columns.str.replace(r'[^\w\s]', '', regex=True)

- Aplico el mismo proceso en las columnas 'provincia', 'partido', 'localidad' y 'poblacion'

In [12]:
# Normalizar valores en columnas específicas
df_mapa['provincia'] = df_mapa['provincia'].str.lower().str.replace(' ', '_').str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8').str.replace(r'[^\w\s]', '', regex=True)
df_mapa['partido'] = df_mapa['partido'].str.lower().str.replace(' ', '_').str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8').str.replace(r'[^\w\s]', '', regex=True)
df_mapa['localidad'] = df_mapa['localidad'].str.lower().str.replace(' ', '_').str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8').str.replace(r'[^\w\s]', '', regex=True)

In [13]:
df_mapa

,provincia,partido,localidad,poblacion,adsl,cablemodem,dial_up,fibra_optica,satelital,wireless,telefonia_fija,3g,4g,link,latitud,longitud
0,buenos_aires,25_de_mayo,25_de_mayo,23408,SI,SI,--,--,SI,SI,SI,SI,SI,6854100.0,-35.433939,-60.173121
1,buenos_aires,25_de_mayo,agustin_mosconi,280,--,--,--,--,--,--,SI,--,--,6854010.0,-35.739217,-60.559063
2,buenos_aires,25_de_mayo,del_valle,899,SI,--,--,--,SI,--,--,SI,--,6854020.0,-35.897345,-60.731609
3,buenos_aires,25_de_mayo,ernestina,145,SI,--,--,--,--,--,SI,--,--,6854030.0,-35.270234,-59.557503
4,buenos_aires,25_de_mayo,gobernador_ugarte,547,--,--,--,--,--,SI,--,--,--,6854040.0,-35.164397,-60.081358
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4300,santa_fe,general_lopez,wheelwright,5733,--,SI,--,SI,SI,SI,SI,SI,SI,82042310.0,-33.794294,-61.211441
4301,santa_fe,general_obligado,arroyo_ceibal,622,--,--,--,--,--,SI,SI,--,SI,82049010.0,-28.725087,-59.480416
4302,santa_fe,general_obligado,avellaneda_est_ewald,23341,SI,--,--,SI,--,SI,SI,SI,SI,82049020.0,-29.119366,-59.659251
4303,santa_fe,general_obligado,berna,629,--,--,--,--,--,SI,SI,--,SI,82049030.0,-29.275268,-59.847222
4304,santa_fe,general_obligado,el_araza,550,--,--,--,--,--,SI,SI,--,SI,82049040.0,-29.133494,-59.947315

Reemplazo los guiones '--' por 'NO'

In [14]:
# Reemplazar '--' por 'NO'
df_mapa.replace('--', 'NO', inplace=True)
df_mapa

,provincia,partido,localidad,poblacion,adsl,cablemodem,dial_up,fibra_optica,satelital,wireless,telefonia_fija,3g,4g,link,latitud,longitud
0,buenos_aires,25_de_mayo,25_de_mayo,23408,SI,SI,NO,NO,SI,SI,SI,SI,SI,6854100.0,-35.433939,-60.173121
1,buenos_aires,25_de_mayo,agustin_mosconi,280,NO,NO,NO,NO,NO,NO,SI,NO,NO,6854010.0,-35.739217,-60.559063
2,buenos_aires,25_de_mayo,del_valle,899,SI,NO,NO,NO,SI,NO,NO,SI,NO,6854020.0,-35.897345,-60.731609
3,buenos_aires,25_de_mayo,ernestina,145,SI,NO,NO,NO,NO,NO,SI,NO,NO,6854030.0,-35.270234,-59.557503
4,buenos_aires,25_de_mayo,gobernador_ugarte,547,NO,NO,NO,NO,NO,SI,NO,NO,NO,6854040.0,-35.164397,-60.081358
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4300,santa_fe,general_lopez,wheelwright,5733,NO,SI,NO,SI,SI,SI,SI,SI,SI,82042310.0,-33.794294,-61.211441
4301,santa_fe,general_obligado,arroyo_ceibal,622,NO,NO,NO,NO,NO,SI,SI,NO,SI,82049010.0,-28.725087,-59.480416
4302,santa_fe,general_obligado,avellaneda_est_ewald,23341,SI,NO,NO,SI,NO,SI,SI,SI,SI,82049020.0,-29.119366,-59.659251
4303,santa_fe,general_obligado,berna,629,NO,NO,NO,NO,NO,SI,SI,NO,SI,82049030.0,-29.275268,-59.847222
4304,santa_fe,general_obligado,el_araza,550,NO,NO,NO,NO,NO,SI,SI,NO,SI,82049040.0,-29.133494,-59.947315

- Convierto la columna 'link' a entero

In [15]:
df_mapa['link'] = df_mapa['link'].astype(int)

- Renombro la columna 'link' a 'link_indec' para unirlo con notebook 'etleda_hoja2'

In [16]:
df_mapa.rename(columns={'link': 'link_indec'}, inplace=True)

In [17]:
df_mapa.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4293 entries, 0 to 4304
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   provincia       4293 non-null   object
 1   partido         4293 non-null   object
 2   localidad       4293 non-null   object
 3   poblacion       4293 non-null   int64
 4   adsl            4293 non-null   object
 5   cablemodem      4293 non-null   object
 6   dial_up         4293 non-null   object
 7   fibra_optica    4293 non-null   object
 8   satelital       4293 non-null   object
 9   wireless        4293 non-null   object
 10  telefonia_fija  4293 non-null   object
 11  3g              4293 non-null   object
 12  4g              4293 non-null   object
 13  link_indec      4293 non-null   int64
 14  latitud         4293 non-null   float64
 15  longitud        4293 non-null   float64
dtypes: float64(2), int64(2), object(12)
memory usage: 570.2+ KB

# Exporto el dataframe para usarlo en conjunto con el dataset de Internet procesado.

In [18]:
df_mapa.to_csv('../datasets/procesado/mapa_conectividad.csv', index=False)